import json

# Read translations
with open('locales/en.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
t = data['landing']

# Build the landing page
lines = []
lines.append('"use client";')
lines.append('')
lines.append('import { useState } from "react";')
lines.append('import Link from "next/link";')
lines.append('import { useTranslations } from "next-intl";')
lines.append('import {')
lines.append('  Sparkles, LayoutDashboard, ArrowRight, Play, Star, CheckCircle,')
lines.append('  Users, Zap, Video, BookOpen, MessageSquare, TrendingUp, Award,')
lines.append('  Shield, Globe, Clock, ChevronDown, Quote, X,')
lines.append('} from "lucide-react";')
lines.append('import { Button } from "@/components/ui/button";')
lines.append('import { Card, CardContent } from "@/components/ui/card";')
lines.append('import { Badge } from "@/components/ui/badge";')
lines.append('import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";')
lines.append('import { LanguageSelector } from "@/components/LanguageSelector";')
lines.append('')
lines.append('export default function Home() {')
lines.append('  const [showDemoModal, setShowDemoModal] = useState(false);')
lines.append('  const t = useTranslations("landing");')
lines.append('')
lines.append('  return (')
lines.append('    <div className="min-h-screen bg-background">')

# Navigation
lines.append('      {/* Navigation */}')
lines.append('      <nav className="fixed top-0 w-full z-50 glass-strong border-b">')
lines.append('        <div className="container mx-auto px-4 h-16 flex items-center justify-between">')
lines.append('          <div className="flex items-center gap-2">')
lines.append('            <div className="w-8 h-8 bg-gradient-to-br from-primary to-purple-600 rounded-lg flex items-center justify-center">')
lines.append('              <Sparkles className="w-5 h-5 text-white" />')
lines.append('            </div>')
lines.append('            <span className="text-xl font-bold">Unytea</span>')
lines.append('          </div>')
lines.append('          <div className="hidden md:flex items-center gap-6">')
lines.append('            <Link href="#features" className="text-sm font-medium hover:text-primary transition-colors">{t("nav.features")}</Link>')
lines.append('            <Link href="#testimonials" className="text-sm font-medium hover:text-primary transition-colors">{t("nav.testimonials")}</Link>')
lines.append('            <Link href="#pricing" className="text-sm font-medium hover:text-primary transition-colors">{t("nav.pricing")}</Link>')
lines.append('            <Link href="#faq" className="text-sm font-medium hover:text-primary transition-colors">{t("nav.faq")}</Link>')
lines.append('          </div>')
lines.append('          <div className="flex items-center gap-3">')
lines.append('            <LanguageSelector />')
lines.append('            <Link href="/dashboard" className="btn-hover-lift px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium shadow-smooth flex items-center gap-2">')
lines.append('              <LayoutDashboard className="w-4 h-4" />')
lines.append('              {t("nav.goToDashboard")}')
lines.append('            </Link>')
lines.append('          </div>')
lines.append('        </div>')
lines.append('      </nav>')

with open('app/[locale]/page.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Landing page header created successfully!')

# Continue building the file
with open('app/[locale]/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('      {/* Hero Section */}\n')
    f.write('      <section className="relative min-h-[85vh] flex items-center overflow-hidden">\n')
    f.write('        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-purple-600/5 to-background" />\n')
    f.write('        <div className="absolute inset-0 bg-gradient-to-b from-background via-transparent to-background/80" />\n')
    f.write('        <div className="container mx-auto px-4 relative z-10 py-20 lg:py-28">\n')
    f.write('          <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center max-w-7xl mx-auto">\n')
    f.write('            <div className="text-center lg:text-left">\n')
    f.write('              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6">\n')
    f.write('                <Star className="w-4 h-4 text-yellow-500 fill-yellow-500" />\n')
    f.write('                <span className="text-sm font-medium">{t("hero.badge")}</span>\n')
    f.write('              </div>\n')
    f.write('              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-4 leading-tight">\n')
    f.write('                {t("hero.title")}\n')
    f.write('              </h1>\n')
    f.write('              <p className="text-lg md:text-xl text-muted-foreground mb-6 max-w-xl mx-auto lg:mx-0">\n')
    f.write('                {t("hero.description")}\n')
    f.write('              </p>\n')
    f.write('              <div className="flex flex-col sm:flex-row gap-3 justify-center lg:justify-start items-center mb-6">\n')
    f.write('                <Link\n')
    f.write('                  href="/auth/signup"\n')
    f.write('                  className="btn-hover-lift px-6 py-3 bg-primary text-primary-foreground rounded-xl text-base font-semibold shadow-smooth-lg inline-flex items-center gap-2 group"\n')
    f.write('                >\n')
    f.write('                  {t("hero.cta.primary")}\n')
    f.write('                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />\n')
    f.write('                </Link>\n')
    f.write('                <button \n')
    f.write('                  onClick={() => setShowDemoModal(true)}\n')
    f.write('                  className="btn-hover-lift px-6 py-3 glass-strong rounded-xl text-base font-semibold inline-flex items-center gap-2 group"\n')
    f.write('                >\n')
    f.write('                  <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center">\n')
    f.write('                    <Play className="w-4 h-4 text-primary fill-primary" />\n')
    f.write('                  </div>\n')
    f.write('                  {t("hero.cta.secondary")}\n')
    f.write('                </button>\n')
    f.write('              </div>\n')
    f.write('              <div className="flex flex-wrap items-center justify-center lg:justify-start gap-6 text-sm text-muted-foreground">\n')
    f.write('                <div className="flex items-center gap-2">\n')
    f.write('                  <div className="flex -space-x-2">\n')
    f.write('                    {[1, 2, 3, 4].map((i) => (\n')
    f.write('                      <Avatar key={i} className="w-7 h-7 border-2 border-background">\n')
    f.write('                        <AvatarImage src={https://i.pravatar.cc/150?img=} />\n')
    f.write('                        <AvatarFallback>U{i}</AvatarFallback>\n')
    f.write('                      </Avatar>\n')
    f.write('                    ))}\n')
    f.write('                  </div>\n')
    f.write('                  <span>{t("hero.socialProof.members")}</span>\n')
    f.write('                </div>\n')
    f.write('                <div className="flex items-center gap-0.5">\n')
    f.write('                  {[...Array(5)].map((_, i) => (\n')
    f.write('                    <Star key={i} className="w-4 h-4 text-yellow-500 fill-yellow-500" />\n')
    f.write('                  ))}\n')
    f.write('                  <span className="ml-2">{t("hero.socialProof.rating")}</span>\n')
    f.write('                </div>\n')
    f.write('              </div>\n')
    f.write('            </div>\n')

print('Hero section added!')

# Dashboard mockup (right column)
with open('app/[locale]/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('            {/* Right Column - Dashboard Mockup */}\n')
    f.write('            <div className="relative hidden lg:block">\n')
    f.write('              <div className="relative rounded-2xl overflow-hidden shadow-2xl border border-border/50 bg-card">\n')
    f.write('                <div className="flex items-center gap-2 px-4 py-3 border-b border-border/50 bg-muted/50">\n')
    f.write('                  <div className="flex gap-1.5">\n')
    f.write('                    <div className="w-3 h-3 rounded-full bg-red-400" />\n')
    f.write('                    <div className="w-3 h-3 rounded-full bg-yellow-400" />\n')
    f.write('                    <div className="w-3 h-3 rounded-full bg-green-400" />\n')
    f.write('                  </div>\n')
    f.write('                  <div className="flex-1 text-center">\n')
    f.write('                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-background text-xs text-muted-foreground">\n')
    f.write('                      <span className="w-3 h-3 rounded-full bg-primary/20" />\n')
    f.write('                      unytea.com/dashboard\n')
    f.write('                    </div>\n')
    f.write('                  </div>\n')
    f.write('                </div>\n')
    f.write('                <div className="p-4 space-y-3">\n')
    f.write('                  <div className="grid grid-cols-3 gap-3">\n')
    f.write('                    {[\n')
    f.write('                      { label: "Members", value: "2,847", icon: Users },\n')
    f.write('                      { label: "Revenue", value: ".4K", icon: Zap },\n')
    f.write('                      { label: "Engagement", value: "94%", icon: TrendingUp },\n')
    f.write('                    ].map((stat, i) => (\n')
    f.write('                      <div key={i} className="bg-muted/50 rounded-lg p-3">\n')
    f.write('                        <div className="flex items-center gap-2 text-muted-foreground text-xs mb-1">\n')
    f.write('                          <stat.icon className="w-3 h-3" />\n')
    f.write('                          {stat.label}\n')
    f.write('                        </div>\n')
    f.write('                        <div className="text-lg font-bold">{stat.value}</div>\n')
    f.write('                      </div>\n')
    f.write('                    ))}\n')
    f.write('                  </div>\n')
    f.write('                  <div className="space-y-2">\n')
    f.write('                    {[1, 2].map((i) => (\n')
    f.write('                      <div key={i} className="flex gap-3 p-3 bg-muted/30 rounded-lg">\n')
    f.write('                        <div className="w-8 h-8 rounded-full bg-primary/20 flex-shrink-0" />\n')
    f.write('                        <div className="flex-1 space-y-1.5">\n')
    f.write('                          <div className="h-3 bg-muted rounded w-1/3" />\n')
    f.write('                          <div className="h-2 bg-muted/50 rounded w-full" />\n')
    f.write('                          <div className="h-2 bg-muted/50 rounded w-2/3" />\n')
    f.write('                        </div>\n')
    f.write('                      </div>\n')
    f.write('                    ))}\n')
    f.write('                  </div>\n')
    f.write('                  <div className="flex gap-3 p-3 bg-gradient-to-r from-primary/5 to-purple-600/5 rounded-lg border border-primary/10">\n')
    f.write('                    <div className="w-12 h-12 rounded-lg bg-primary/20 flex items-center justify-center flex-shrink-0">\n')
    f.write('                      <BookOpen className="w-6 h-6 text-primary" />\n')
    f.write('                    </div>\n')
    f.write('                    <div className="flex-1">\n')
    f.write('                      <div className="font-medium text-sm">Community Mastery</div>\n')
    f.write('                      <div className="text-xs text-muted-foreground">247 students enrolled</div>\n')
    f.write('                      <div className="mt-2 h-1.5 bg-muted rounded-full overflow-hidden">\n')
    f.write('                        <div className="h-full w-3/4 bg-primary rounded-full" />\n')
    f.write('                      </div>\n')
    f.write('                    </div>\n')
    f.write('                  </div>\n')
    f.write('                </div>\n')
    f.write('              </div>\n')
    f.write('              <div className="absolute -top-4 -right-4 w-24 h-24 bg-primary/20 rounded-full blur-2xl" />\n')
    f.write('              <div className="absolute -bottom-4 -left-4 w-32 h-32 bg-purple-600/20 rounded-full blur-2xl" />\n')
    f.write('            </div>\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 animate-bounce">\n')
    f.write('          <ChevronDown className="w-5 h-5 text-muted-foreground" />\n')
    f.write('        </div>\n')
    f.write('      </section>\n')

print('Dashboard mockup added!')

# Stats Section
with open('app/[locale]/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('      {/* Stats Section */}\n')
    f.write('      <section className="py-16 px-4 border-y border-border/50 bg-muted/30">\n')
    f.write('        <div className="container mx-auto max-w-6xl">\n')
    f.write('          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">\n')
    f.write('            <div>\n')
    f.write('              <p className="text-4xl md:text-5xl font-bold gradient-text">10K+</p>\n')
    f.write('              <p className="text-muted-foreground mt-2">{t("stats.communities")}</p>\n')
    f.write('            </div>\n')
    f.write('            <div>\n')
    f.write('              <p className="text-4xl md:text-5xl font-bold gradient-text">500K+</p>\n')
    f.write('              <p className="text-muted-foreground mt-2">{t("stats.members")}</p>\n')
    f.write('            </div>\n')
    f.write('            <div>\n')
    f.write('              <p className="text-4xl md:text-5xl font-bold gradient-text">+</p>\n')
    f.write('              <p className="text-muted-foreground mt-2">{t("stats.revenue")}</p>\n')
    f.write('            </div>\n')
    f.write('            <div>\n')
    f.write('              <p className="text-4xl md:text-5xl font-bold gradient-text">98%</p>\n')
    f.write('              <p className="text-muted-foreground mt-2">{t("stats.satisfaction")}</p>\n')
    f.write('            </div>\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </section>\n')

print('Stats section added!')

# Instructor Section
with open('app/[locale]/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('      {/* Instructor Spotlight */}\n')
    f.write('      <section className="py-20 px-4">\n')
    f.write('        <div className="container mx-auto max-w-6xl">\n')
    f.write('          <div className="grid md:grid-cols-2 gap-12 items-center">\n')
    f.write('            <div className="relative">\n')
    f.write('              <div className="absolute -inset-4 bg-gradient-to-r from-primary/20 to-purple-600/20 rounded-3xl blur-2xl" />\n')
    f.write('              <div className="relative aspect-square rounded-2xl overflow-hidden">\n')
    f.write('                <img\n')
    f.write('                  src="https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&h=600&fit=crop"\n')
    f.write('                  alt="Lead Instructor"\n')
    f.write('                  className="w-full h-full object-cover"\n')
    f.write('                />\n')
    f.write('              </div>\n')
    f.write('              <div className="absolute -bottom-4 -right-4 bg-card rounded-xl p-4 shadow-xl border">\n')
    f.write('                <div className="flex items-center gap-3">\n')
    f.write('                  <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center">\n')
    f.write('                    <CheckCircle className="w-6 h-6 text-green-600" />\n')
    f.write('                  </div>\n')
    f.write('                  <div>\n')
    f.write('                    <p className="font-semibold">{t("instructor.verified")}</p>\n')
    f.write('                  </div>\n')
    f.write('                </div>\n')
    f.write('              </div>\n')
    f.write('            </div>\n')
    f.write('            <div className="space-y-6">\n')
    f.write('              <Badge className="bg-primary/10 text-primary hover:bg-primary/20">{t("instructor.badge")}</Badge>\n')
    f.write('              <p className="text-lg text-muted-foreground">{t("instructor.bio")}</p>\n')
    f.write('              <Link href="/auth/signup">\n')
    f.write('                <Button size="lg" className="mt-4">\n')
    f.write('                  {t("hero.cta.primary")}\n')
    f.write('                  <ArrowRight className="w-4 h-4 ml-2" />\n')
    f.write('                </Button>\n')
    f.write('              </Link>\n')
    f.write('            </div>\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </section>\n')

print('Instructor section added!')
